USE APP_ROBERTO
GO

-- Elimina primero los registros de tablas 
DELETE FROM PUNTAJE;
DELETE FROM OPCION;
DELETE FROM PREGUNTA;
DELETE FROM JUEGO_PACIENTE;
DELETE FROM EVENTO_USUARIO;
DELETE FROM CUIDADOR_PACIENTE;
DELETE FROM PING;
DELETE FROM MENSAJE;
DELETE FROM SESION;
DELETE FROM IMAGEN;
DELETE FROM JUEGO;
DELETE FROM EVENTO;
DELETE FROM USUARIO;

-- Reinicia el identity para que el id sea asignado desde el #1 desde el inicio
DBCC CHECKIDENT ('PUNTAJE', RESEED, 0);
DBCC CHECKIDENT ('PREGUNTA', RESEED, 0);
DBCC CHECKIDENT ('MENSAJE', RESEED, 0);
DBCC CHECKIDENT ('SESION', RESEED, 0);
DBCC CHECKIDENT ('IMAGEN', RESEED, 0);
DBCC CHECKIDENT ('JUEGO', RESEED, 0);
DBCC CHECKIDENT ('EVENTO', RESEED, 0);
DBCC CHECKIDENT ('USUARIO', RESEED, 0);
DBCC CHECKIDENT ('PING', RESEED, 0);


INSERT INTO USUARIO(NOMBRE,CORREO_ELECTRONICO,CONTRASENA,FECHA_NACIMIENTO,FOTO_PERFIL,CODIGO,DIRECCION,ID_TIPO_USUARIO)
	VALUES ('Roberto Perez', 'CorreoElectronico@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '123ABC', 'Alajuela', 1),
		('Roberto Castrillo', 'CorreoElectronico69@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 2),
		('Roberto Morales', 'CorreoElectronico59@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 2),
		('Roberto Ramirez', 'CorreoElectronico65@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 2),
		('Roberto Calderon', 'CorreoElectronico885@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 1),
		('Carlos Calderon', 'CoorreoElectronico885@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 1),
		('Carlos Perez', 'CoorreoElectronico8865@gmail.com', 'P@ssw0rd123!', '2025-03-20', NULL, '456DEF', 'Alajuela', 1);




INSERT INTO SESION(TOKEN,ID_USUARIO,ORIGEN,FECHA_INICIO,FECHA_EXPIRACION,FECHA_FINAL)
	VALUES ('9004B3DC-EDBE-4EFF-9F04-4006419A9B3A', 1, 'ORIGEN', GETDATE(), DATEADD(DAY, 7, GETDATE()), NULL),
		('DE05D71F-9771-42D7-83E7-2ECA8CCD1465', 2, 'ORIGEN', GETDATE(), DATEADD(DAY, 7, GETDATE()), NULL);

INSERT INTO CUIDADOR_PACIENTE(ID_USUARIO_CUIDADOR,ID_USUARIO_PACIENTE, FEC_INICIO, FEC_FIN)
	VALUES (3, 1, GETDATE(), NULL),
	(4, 1, GETDATE(), NULL);

INSERT INTO PING(CODIGO,FECHA,ESTADO,ID_USUARIO)
	VALUES ('123123', GETDATE(), 1, 6),
		('222111', GETDATE(), 1, 7);


