#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="APP_ROBERTO")]
	public partial class MiLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public MiLinqDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.APP_ROBERTOConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MiLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_CONTRASENA")]
		public int SP_ACTUALIZAR_CONTRASENA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA_ACTUAL", DbType="VarChar(255)")] string cONTRASENA_ACTUAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVA_CONTRASENA", DbType="VarChar(255)")] string nUEVA_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(6)")] string pIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, cONTRASENA_ACTUAL, nUEVA_CONTRASENA, pIN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_RELACION")]
		public ISingleResult<SP_OBTENER_RELACIONResult> SP_OBTENER_RELACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_RELACIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_ESTADO_MENSAJES")]
		public int SP_ACTUALIZAR_ESTADO_MENSAJES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MENSAJE", DbType="Int")] System.Nullable<int> iD_MENSAJE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PACIENTE, iD_MENSAJE, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_EVENTO")]
		public int SP_ACTUALIZAR_EVENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EVENTO", DbType="Int")] System.Nullable<int> iD_EVENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITULO", DbType="VarChar(255)")] string tITULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_HORA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_HORA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRIORIDAD", DbType="Int")] System.Nullable<int> iD_PRIORIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EVENTO, iD_CUIDADOR, tITULO, dESCRIPCION, fECHA_HORA, iD_PRIORIDAD, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRROR_CODE = ((string)(result.GetParameterValue(7)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_FOTO_PERFIL")]
		public int SP_ACTUALIZAR_FOTO_PERFIL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FOTO_PERFIL", DbType="VarBinary(MAX)")] System.Data.Linq.Binary fOTO_PERFIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, fOTO_PERFIL, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_PING")]
		public int SP_ACTUALIZAR_PING([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN_ACTUAL", DbType="VarChar(6)")] string pIN_ACTUAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_CODIGO", DbType="VarChar(6)")] string nUEVO_CODIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, pIN_ACTUAL, nUEVO_CODIGO, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_USUARIO")]
		public int SP_ACTUALIZAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="VarChar(255)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PIN", DbType="VarChar(6)")] string pIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, nOMBRE, fECHA_NACIMIENTO, dIRECCION, pIN, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRROR_CODE = ((string)(result.GetParameterValue(7)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_SESION")]
		public int SP_CERRAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORIGEN", DbType="NVarChar(MAX)")] string oRIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, oRIGEN, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CONSULTAR_SESION")]
		public ISingleResult<SP_CONSULTAR_SESIONResult> SP_CONSULTAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN", DbType="NVarChar(MAX)")] string tOKEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_CONSULTAR_SESIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_EVENTO")]
		public int SP_ELIMINAR_EVENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EVENTO", DbType="Int")] System.Nullable<int> iD_EVENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EVENTO, iD_CUIDADOR, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_FOTO_PERFIL")]
		public int SP_ELIMINAR_FOTO_PERFIL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PING", DbType="VarChar(6)")] string cODIGO_PING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, cODIGO_PING, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_JUEGO")]
		public int SP_ELIMINAR_JUEGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_JUEGO", DbType="Int")] System.Nullable<int> iD_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_JUEGO, iD_CUIDADOR, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_PACIENTE_EVENTO")]
		public int SP_ELIMINAR_PACIENTE_EVENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EVENTO", DbType="Int")] System.Nullable<int> iD_EVENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EVENTO, iD_CUIDADOR, iD_PACIENTE, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_PING")]
		public int SP_ELIMINAR_PING([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PING", DbType="VarChar(6)")] string cODIGO_PING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, cODIGO_PING, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_RELACION")]
		public int SP_ELIMINAR_RELACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO_CUIDADOR", DbType="Int")] System.Nullable<int> iD_USUARIO_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO_PACIENTE", DbType="Int")] System.Nullable<int> iD_USUARIO_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PING", DbType="VarChar(6)")] string cODIGO_PING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO_CUIDADOR, iD_USUARIO_PACIENTE, cODIGO_PING, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_EVENTO")]
		public int SP_INSERTAR_EVENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITULO", DbType="VarChar(255)")] string tITULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_HORA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_HORA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PRIORIDAD", DbType="Int")] System.Nullable<int> iD_PRIORIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, tITULO, dESCRIPCION, fECHA_HORA, iD_PRIORIDAD, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRROR_CODE = ((string)(result.GetParameterValue(7)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_JUEGO")]
		public int SP_INSERTAR_JUEGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(255)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, nOMBRE, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_MENSAJE")]
		public int SP_INSERTAR_MENSAJE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTENIDO", DbType="VarChar(255)")] string cONTENIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, iD_PACIENTE, cONTENIDO, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_OPCION")]
		public int SP_INSERTAR_OPCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PREGUNTA", DbType="Int")] System.Nullable<int> iD_PREGUNTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONDICION", DbType="Bit")] System.Nullable<bool> cONDICION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PREGUNTA, iD_CUIDADOR, dESCRIPCION, cONDICION, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRROR_CODE = ((string)(result.GetParameterValue(6)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_PACIENTE_EVENTO")]
		public int SP_INSERTAR_PACIENTE_EVENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EVENTO", DbType="Int")] System.Nullable<int> iD_EVENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_EVENTO, iD_CUIDADOR, iD_PACIENTE, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_PACIENTE_JUEGO")]
		public int SP_INSERTAR_PACIENTE_JUEGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_JUEGO", DbType="Int")] System.Nullable<int> iD_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_JUEGO, iD_CUIDADOR, iD_PACIENTE, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_PING")]
		public int SP_INSERTAR_PING([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="VarChar(6)")] string cODIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, cODIGO, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_PREGUNTA")]
		public int SP_INSERTAR_PREGUNTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_JUEGO", DbType="Int")] System.Nullable<int> iD_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITULO", DbType="VarChar(255)")] string tITULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(MAX)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BINARIO_FOTO", DbType="VarBinary(MAX)")] System.Data.Linq.Binary bINARIO_FOTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_JUEGO, tITULO, dESCRIPCION, bINARIO_FOTO, iD_USUARIO, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRROR_CODE = ((string)(result.GetParameterValue(7)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_RELACION")]
		public int SP_INSERTAR_RELACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO_CUIDADOR", DbType="Int")] System.Nullable<int> iD_USUARIO_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PACIENTE", DbType="VarChar(6)")] string cODIGO_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO_CUIDADOR, cODIGO_PACIENTE, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_CODE = ((string)(result.GetParameterValue(4)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_SESION")]
		public ISingleResult<SP_INSERTAR_SESIONResult> SP_INSERTAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORIGEN", DbType="NVarChar(MAX)")] string oRIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, pASSWORD, oRIGEN, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRROR_CODE = ((string)(result.GetParameterValue(5)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(6)));
			return ((ISingleResult<SP_INSERTAR_SESIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_USUARIO")]
		public int SP_INSERTAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(255)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(255)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FOTO_PERFIL", DbType="VarBinary(MAX)")] System.Data.Linq.Binary fOTO_PERFIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="VarChar(255)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TIPO_USUARIO", DbType="Int")] System.Nullable<int> iD_TIPO_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, cORREO_ELECTRONICO, cONTRASENA, fECHA_NACIMIENTO, fOTO_PERFIL, dIRECCION, iD_TIPO_USUARIO, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRROR_CODE = ((string)(result.GetParameterValue(9)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_EVENTOS_CUIDADOR")]
		public ISingleResult<SP_OBTENER_EVENTOS_CUIDADORResult> SP_OBTENER_EVENTOS_CUIDADOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_EVENTOS_CUIDADORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_EVENTOS_PACIENTE")]
		public ISingleResult<SP_OBTENER_EVENTOS_PACIENTEResult> SP_OBTENER_EVENTOS_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PACIENTE, iD_RETURN, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRROR_CODE = ((string)(result.GetParameterValue(3)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_OBTENER_EVENTOS_PACIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_JUEGOS_CREADOS")]
		public ISingleResult<SP_OBTENER_JUEGOS_CREADOSResult> SP_OBTENER_JUEGOS_CREADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CUIDADOR", DbType="Int")] System.Nullable<int> iD_CUIDADOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CUIDADOR, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_JUEGOS_CREADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_JUEGOS_DISPONIBLES")]
		public ISingleResult<SP_OBTENER_JUEGOS_DISPONIBLESResult> SP_OBTENER_JUEGOS_DISPONIBLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PACIENTE, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_JUEGOS_DISPONIBLESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_MENSAJES")]
		public ISingleResult<SP_OBTENER_MENSAJESResult> SP_OBTENER_MENSAJES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PACIENTE, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_MENSAJESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PREGUNTAS")]
		public ISingleResult<SP_OBTENER_PREGUNTASResult> SP_OBTENER_PREGUNTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_JUEGO", DbType="Int")] System.Nullable<int> iD_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_JUEGO, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_PREGUNTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PUNTAJE")]
		public ISingleResult<SP_OBTENER_PUNTAJEResult> SP_OBTENER_PUNTAJE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PACIENTE", DbType="Int")] System.Nullable<int> iD_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_CODE", DbType="NVarChar(255)")] ref string eRROR_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPTION", DbType="NVarChar(MAX)")] ref string eRROR_DESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PACIENTE, eRROR_ID, eRROR_CODE, eRROR_DESCRIPTION);
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRROR_CODE = ((string)(result.GetParameterValue(2)));
			eRROR_DESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_OBTENER_PUNTAJEResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_RELACIONResult
	{
		
		private int _ID_PACIENTE;
		
		private string _NOMBRE;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		public SP_OBTENER_RELACIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PACIENTE", DbType="Int NOT NULL")]
		public int ID_PACIENTE
		{
			get
			{
				return this._ID_PACIENTE;
			}
			set
			{
				if ((this._ID_PACIENTE != value))
				{
					this._ID_PACIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
	}
	
	public partial class SP_CONSULTAR_SESIONResult
	{
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private System.Data.Linq.Binary _FOTO_PERFIL;
		
		private string _CODIGO;
		
		private string _DIRECCION;
		
		private int _ID_TIPO_USUARIO;
		
		public SP_CONSULTAR_SESIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_PERFIL", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FOTO_PERFIL
		{
			get
			{
				return this._FOTO_PERFIL;
			}
			set
			{
				if ((this._FOTO_PERFIL != value))
				{
					this._FOTO_PERFIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="VarChar(6)")]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(255)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_USUARIO", DbType="Int NOT NULL")]
		public int ID_TIPO_USUARIO
		{
			get
			{
				return this._ID_TIPO_USUARIO;
			}
			set
			{
				if ((this._ID_TIPO_USUARIO != value))
				{
					this._ID_TIPO_USUARIO = value;
				}
			}
		}
	}
	
	public partial class SP_INSERTAR_SESIONResult
	{
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _CORREO_ELECTRONICO;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private System.Data.Linq.Binary _FOTO_PERFIL;
		
		private string _CODIGO;
		
		private string _DIRECCION;
		
		private int _ID_TIPO_USUARIO;
		
		private string _TOKEN_SESION;
		
		private System.Nullable<System.DateTime> _EXPIRACION;
		
		public SP_INSERTAR_SESIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_PERFIL", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FOTO_PERFIL
		{
			get
			{
				return this._FOTO_PERFIL;
			}
			set
			{
				if ((this._FOTO_PERFIL != value))
				{
					this._FOTO_PERFIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="VarChar(6)")]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(255)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_USUARIO", DbType="Int NOT NULL")]
		public int ID_TIPO_USUARIO
		{
			get
			{
				return this._ID_TIPO_USUARIO;
			}
			set
			{
				if ((this._ID_TIPO_USUARIO != value))
				{
					this._ID_TIPO_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOKEN_SESION", DbType="NVarChar(255)")]
		public string TOKEN_SESION
		{
			get
			{
				return this._TOKEN_SESION;
			}
			set
			{
				if ((this._TOKEN_SESION != value))
				{
					this._TOKEN_SESION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPIRACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXPIRACION
		{
			get
			{
				return this._EXPIRACION;
			}
			set
			{
				if ((this._EXPIRACION != value))
				{
					this._EXPIRACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_EVENTOS_CUIDADORResult
	{
		
		private int _ID_EVENTO;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private System.DateTime _FECHA_HORA;
		
		private int _ID_PRIORIDAD;
		
		private string _PRIORIDAD;
		
		private string _PACIENTES;
		
		public SP_OBTENER_EVENTOS_CUIDADORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EVENTO", DbType="Int NOT NULL")]
		public int ID_EVENTO
		{
			get
			{
				return this._ID_EVENTO;
			}
			set
			{
				if ((this._ID_EVENTO != value))
				{
					this._ID_EVENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_HORA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_HORA
		{
			get
			{
				return this._FECHA_HORA;
			}
			set
			{
				if ((this._FECHA_HORA != value))
				{
					this._FECHA_HORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRIORIDAD", DbType="Int NOT NULL")]
		public int ID_PRIORIDAD
		{
			get
			{
				return this._ID_PRIORIDAD;
			}
			set
			{
				if ((this._ID_PRIORIDAD != value))
				{
					this._ID_PRIORIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORIDAD", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PRIORIDAD
		{
			get
			{
				return this._PRIORIDAD;
			}
			set
			{
				if ((this._PRIORIDAD != value))
				{
					this._PRIORIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACIENTES", DbType="NVarChar(MAX)")]
		public string PACIENTES
		{
			get
			{
				return this._PACIENTES;
			}
			set
			{
				if ((this._PACIENTES != value))
				{
					this._PACIENTES = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_EVENTOS_PACIENTEResult
	{
		
		private int _ID_EVENTO;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private System.DateTime _FECHA_HORA;
		
		private int _ID_PRIORIDAD;
		
		private string _PRIORIDAD;
		
		private int _ID_CUIDADOR;
		
		private string _NOMBRE_CUIDADOR;
		
		public SP_OBTENER_EVENTOS_PACIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EVENTO", DbType="Int NOT NULL")]
		public int ID_EVENTO
		{
			get
			{
				return this._ID_EVENTO;
			}
			set
			{
				if ((this._ID_EVENTO != value))
				{
					this._ID_EVENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_HORA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_HORA
		{
			get
			{
				return this._FECHA_HORA;
			}
			set
			{
				if ((this._FECHA_HORA != value))
				{
					this._FECHA_HORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRIORIDAD", DbType="Int NOT NULL")]
		public int ID_PRIORIDAD
		{
			get
			{
				return this._ID_PRIORIDAD;
			}
			set
			{
				if ((this._ID_PRIORIDAD != value))
				{
					this._ID_PRIORIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORIDAD", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PRIORIDAD
		{
			get
			{
				return this._PRIORIDAD;
			}
			set
			{
				if ((this._PRIORIDAD != value))
				{
					this._PRIORIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUIDADOR", DbType="Int NOT NULL")]
		public int ID_CUIDADOR
		{
			get
			{
				return this._ID_CUIDADOR;
			}
			set
			{
				if ((this._ID_CUIDADOR != value))
				{
					this._ID_CUIDADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CUIDADOR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CUIDADOR
		{
			get
			{
				return this._NOMBRE_CUIDADOR;
			}
			set
			{
				if ((this._NOMBRE_CUIDADOR != value))
				{
					this._NOMBRE_CUIDADOR = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_JUEGOS_CREADOSResult
	{
		
		private int _ID_JUEGO;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _TOTAL_PREGUNTAS;
		
		public SP_OBTENER_JUEGOS_CREADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JUEGO", DbType="Int NOT NULL")]
		public int ID_JUEGO
		{
			get
			{
				return this._ID_JUEGO;
			}
			set
			{
				if ((this._ID_JUEGO != value))
				{
					this._ID_JUEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PREGUNTAS", DbType="Int")]
		public System.Nullable<int> TOTAL_PREGUNTAS
		{
			get
			{
				return this._TOTAL_PREGUNTAS;
			}
			set
			{
				if ((this._TOTAL_PREGUNTAS != value))
				{
					this._TOTAL_PREGUNTAS = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_JUEGOS_DISPONIBLESResult
	{
		
		private int _ID_JUEGO;
		
		private string _NOMBRE;
		
		private System.Nullable<int> _TOTAL_PREGUNTAS;
		
		public SP_OBTENER_JUEGOS_DISPONIBLESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JUEGO", DbType="Int NOT NULL")]
		public int ID_JUEGO
		{
			get
			{
				return this._ID_JUEGO;
			}
			set
			{
				if ((this._ID_JUEGO != value))
				{
					this._ID_JUEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PREGUNTAS", DbType="Int")]
		public System.Nullable<int> TOTAL_PREGUNTAS
		{
			get
			{
				return this._TOTAL_PREGUNTAS;
			}
			set
			{
				if ((this._TOTAL_PREGUNTAS != value))
				{
					this._TOTAL_PREGUNTAS = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_MENSAJESResult
	{
		
		private int _ID_MENSAJE;
		
		private string _CONTENIDO;
		
		private System.Nullable<System.DateTime> _FECHA_ENVIADO;
		
		private int _ID_CUIDADOR;
		
		private string _NOMBRE_CUIDADOR;
		
		private int _ID_ESTADO;
		
		public SP_OBTENER_MENSAJESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENSAJE", DbType="Int NOT NULL")]
		public int ID_MENSAJE
		{
			get
			{
				return this._ID_MENSAJE;
			}
			set
			{
				if ((this._ID_MENSAJE != value))
				{
					this._ID_MENSAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENIDO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CONTENIDO
		{
			get
			{
				return this._CONTENIDO;
			}
			set
			{
				if ((this._CONTENIDO != value))
				{
					this._CONTENIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ENVIADO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ENVIADO
		{
			get
			{
				return this._FECHA_ENVIADO;
			}
			set
			{
				if ((this._FECHA_ENVIADO != value))
				{
					this._FECHA_ENVIADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUIDADOR", DbType="Int NOT NULL")]
		public int ID_CUIDADOR
		{
			get
			{
				return this._ID_CUIDADOR;
			}
			set
			{
				if ((this._ID_CUIDADOR != value))
				{
					this._ID_CUIDADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CUIDADOR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CUIDADOR
		{
			get
			{
				return this._NOMBRE_CUIDADOR;
			}
			set
			{
				if ((this._NOMBRE_CUIDADOR != value))
				{
					this._NOMBRE_CUIDADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTADO", DbType="Int NOT NULL")]
		public int ID_ESTADO
		{
			get
			{
				return this._ID_ESTADO;
			}
			set
			{
				if ((this._ID_ESTADO != value))
				{
					this._ID_ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PREGUNTASResult
	{
		
		private int _ID_PREGUNTA;
		
		private string _DESCRIPCION;
		
		private System.Data.Linq.Binary _IMAGEN_BINARIA;
		
		private string _OPCIONES;
		
		public SP_OBTENER_PREGUNTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PREGUNTA", DbType="Int NOT NULL")]
		public int ID_PREGUNTA
		{
			get
			{
				return this._ID_PREGUNTA;
			}
			set
			{
				if ((this._ID_PREGUNTA != value))
				{
					this._ID_PREGUNTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN_BINARIA", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary IMAGEN_BINARIA
		{
			get
			{
				return this._IMAGEN_BINARIA;
			}
			set
			{
				if ((this._IMAGEN_BINARIA != value))
				{
					this._IMAGEN_BINARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPCIONES", DbType="NVarChar(MAX)")]
		public string OPCIONES
		{
			get
			{
				return this._OPCIONES;
			}
			set
			{
				if ((this._OPCIONES != value))
				{
					this._OPCIONES = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PUNTAJEResult
	{
		
		private int _ID_PUNTAJE;
		
		private int _ID_JUEGO;
		
		private string _NOMBRE_JUEGO;
		
		private int _PUNTAJE;
		
		private System.Nullable<System.DateTime> _FECHA_HORA;
		
		public SP_OBTENER_PUNTAJEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PUNTAJE", DbType="Int NOT NULL")]
		public int ID_PUNTAJE
		{
			get
			{
				return this._ID_PUNTAJE;
			}
			set
			{
				if ((this._ID_PUNTAJE != value))
				{
					this._ID_PUNTAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JUEGO", DbType="Int NOT NULL")]
		public int ID_JUEGO
		{
			get
			{
				return this._ID_JUEGO;
			}
			set
			{
				if ((this._ID_JUEGO != value))
				{
					this._ID_JUEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_JUEGO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE_JUEGO
		{
			get
			{
				return this._NOMBRE_JUEGO;
			}
			set
			{
				if ((this._NOMBRE_JUEGO != value))
				{
					this._NOMBRE_JUEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNTAJE", DbType="Int NOT NULL")]
		public int PUNTAJE
		{
			get
			{
				return this._PUNTAJE;
			}
			set
			{
				if ((this._PUNTAJE != value))
				{
					this._PUNTAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_HORA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_HORA
		{
			get
			{
				return this._FECHA_HORA;
			}
			set
			{
				if ((this._FECHA_HORA != value))
				{
					this._FECHA_HORA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
